/** The health state of a monitored component or group, as returned by `/api/status`. */
export type StatusLevel = 'operational' | 'degraded' | 'down' | 'unknown'

/** A single monitored component (e.g. one service or endpoint) in a group. */
export interface StatusComponent {
  /** Human-readable display name. */
  name: string
  /** Current health state. */
  status: StatusLevel
}

/** A logical group of related components (e.g. "Infrastructure", "APIs"). */
export interface StatusGroup {
  /** Human-readable group name. */
  name: string
  /** Aggregate status for the group (worst of all components). */
  status: StatusLevel
  /** Individual components in this group. */
  components: StatusComponent[]
}

/** A complete status snapshot as returned by `GET /api/status`. */
export interface StatusSnapshot {
  /** ISO 8601 timestamp when the snapshot was generated by platform-probe. */
  generated_at: string
  /** Aggregate status across all groups (worst level observed). */
  overall: StatusLevel
  /** All status groups in display order. */
  groups: StatusGroup[]
}
